apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: che-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: "nginx"
{{- if .Values.tlsEnabled }}
    kubernetes.io/tls-acme: "true"
{{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
    ingress.kubernetes.io/proxy-read-timeout: "3600"
    ingress.kubernetes.io/proxy-connect-timeout: "3600"
spec:
{{- if .Values.tlsEnabled }}
  tls:
  - hosts:
    - {{ template "cheHost" . }}
    secretName: {{ .Values.tlsSecretName }}
{{- end }}
  rules:
  - host: {{ template "cheHost" . }}
    http:
      paths:
      - backend:
          serviceName: che-host
          servicePort: 8080
        path: /