version: '{build}'
branches:
  only:
  - master
  - 4.0
skip_tags: true
init:
- ps: >-
    $MVNDIR = 'C:\bin\apache-maven-3.3.1\'
          if(!(Test-Path -Path $MVNDIR )){
            Write-Host (Test-Path -Path $MVNDIR)
            Write-Host 'Installing Maven'
            cinst maven -Version 3.3.1
          } else {
            Write-Host 'Found Maven cached installation'
          }
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  JAVA_OPTS: -Xmx2g
install:
- SET PATH=C:\bin\apache-maven-3.3.1\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
- mvn --version
- java -version
cache: C:\bin\apache-maven-3.3.1
build_script:
- mvn -B clean install
