#
# Copyright (c) 2012-2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# Default values for Keycloak
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ingress:
    class: "nginx"
  tls:
    ## Name of the config-map with public certificates to add to Java trust store of the Keycloak
    serverTrustStoreConfigMapName: ""
  # Image used by endpoint watcher (postgres)
  endpointWatcher:
    image: quay.io/eclipse/che-endpoint-watcher:nightly

image: quay.io/eclipse/che-keycloak:7.28.2

## Admin credentials configuration
# Manually define them in clear
requireAdminPasswordChange: true
keycloakAdminUserName: admin
keycloakAdminUserPassword: admin
# Or use a secret with keys 'user' and 'password'
#keycloakCredentialsSecret: che-identity-secret

deploymentStrategy: RollingUpdate
