# Copyright (c) 2012-2017 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout: "3600"
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout: "3600"
{{- if .Values.global.tlsEnabled }}
    kubernetes.io/tls-acme: "true"
{{- else }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
spec:
{{- if .Values.global.tlsEnabled }}
  tls:
  - hosts:
    - {{ template "keycloakHost" . }}
    secretName: keycloak-tls
{{- end }}
  rules:
{{- if .Values.global.isHostBased }}
  - host: {{ template "keycloakHost" . }}
    http:
      paths:
      - path: /
{{- else }}
  - http:
      paths:
      - path: /auth/
{{- end }}
        backend:
          serviceName: keycloak
          servicePort: 5050

