#
# Copyright (c) 2012-2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: marketplace
    name: marketplace
  spec:
    ports:
    - name: marketplace
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: marketplace
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: marketplace
    name: marketplace
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: marketplace
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: marketplace
      spec:
        containers:
          - image: garagatyi/che-marketplace:os
            imagePullPolicy: Always
            name: marketplace-apache
            ports:
            - containerPort: 8080
              name: marketplace
            resources:
              limits:
                memory: 600Mi
              requests:
                memory: 256Mi
