#
# Copyright (c) 2012-2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

dependencies:
  - name: che-devfile-registry
    repository: file://./custom-charts/che-devfile-registry/
    version: 0.0.1
    condition: cheDevfileRegistry.deploy
  - name: che-plugin-registry
    repository: file://./custom-charts/che-plugin-registry/
    version: 0.0.1
    condition: chePluginRegistry.deploy
  - name: che-postgres
    repository: file://./custom-charts/che-postgres/
    version: 1.0.0
    condition: global.multiuser
  - name: che-keycloak
    repository: file://./custom-charts/che-keycloak/
    version: 1.0.0
    condition: global.cheDedicatedKeycloak,global.multiuser
  - name: che-jaeger
    repository: file://./custom-charts/che-jaeger
    version: 1.0.0
    condition: global.tracingEnabled
  - name: prometheus
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: ^9.3.1
    condition: global.metricsEnabled
  - name: grafana
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: ^4.0.3
    condition: global.metricsEnabled
