# Copyright (c) 2012-2017 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

apiVersion: v1
kind: Route
metadata:
  name: "keycloak"
spec:
  port:
    targetPort: '5050'
  to:
    kind: Service
    name: "keycloak"
