---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: che-certificate
  namespace: che
spec:
  secretName: che-tls
  issuerRef:
    name: che-cluster-issuer
    kind: ClusterIssuer
  # This is a template and it will be set from --domain parameter
  # For example: '*.192.168.99.100.nip.io'
  commonName: '*.<domain>'
  dnsNames:
    - '*.<domain>'
