#
# Copyright (c) 2012-2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: che
  name: che
data:
  CHE_HOST: {{ template "cheHost" . }}
  CHE_PORT: "8080"
{{- if and .Values.global.tls .Values.global.tls.enabled }}
  CHE_API: https://{{ template "cheHost" . }}/api
  CHE_WEBSOCKET_ENDPOINT:  wss://{{ template "cheHost" . }}/api/websocket
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: https://{{ template "cheHost" . }}/agent-binaries/linux_amd64/bootstrapper/bootstrapper
{{ else }}
  CHE_API: http://{{ template "cheHost" . }}/api
  CHE_WEBSOCKET_ENDPOINT:  ws://{{ template "cheHost" . }}/api/websocket
  CHE_WEBSOCKET_ENDPOINT__MINOR:  ws://{{ template "cheHost" . }}/api/websocket-minor
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: http://{{ template "cheHost" . }}/agent-binaries/linux_amd64/bootstrapper/bootstrapper
{{- end }}
  CHE_DEBUG_SERVER: "true"
  CHE_INFRASTRUCTURE_ACTIVE: "kubernetes"
  CHE_INFRA_KUBERNETES_INGRESS_DOMAIN: {{ .Values.global.ingressDomain }}
  CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN: "5"
  CHE_INFRA_KUBERNETES_MASTER__URL: ""
{{- if and .Values.global.tls .Values.global.tls.enabled }}
  CHE_INFRA_KUBERNETES_TLS__ENABLED: {{ .Values.global.tls.enabled | quote}}
  CHE_INFRA_KUBERNETES_TLS__SECRET: {{ .Values.global.tls.secretName }}
{{- else }}
  CHE_INFRA_KUBERNETES_TLS__ENABLED: "false"
  CHE_INFRA_KUBERNETES_TLS__SECRET: ""
{{- end }}
{{- if .Values.global.multiuser }}
  CHE_KEYCLOAK_CLIENT__ID: {{ .Values.cheKeycloakClientId | quote}}
  CHE_KEYCLOAK_AUTH__SERVER__URL: {{ template "keycloakAuthUrl" . }}
  CHE_KEYCLOAK_REALM: {{ .Values.cheKeycloakRealm }}
{{- end }}
{{- if (and .Values.global.multiuser .Values.customOidcProvider) }}
  CHE_KEYCLOAK_OIDC__PROVIDER: {{ .Values.customOidcProvider }}
{{- end }}
{{- if and .Values.global.multiuser .Values.customOidcUsernameClaim }}
  CHE_KEYCLOAK_USERNAME__CLAIM: {{ .Values.customOidcUsernameClaim }}
{{- end }}
  CHE_INFRA_KUBERNETES_NAMESPACE: {{ .Values.global.cheWorkspacesNamespace | quote}}
  CHE_INFRA_KUBERNETES_SERVICE__ACCOUNT__NAME: {{ .Values.global.cheWorkspaceServiceAccount }}
  CHE_INFRA_KUBERNETES_TRUST__CERTS: "false"
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: "common"
  CHE_INFRA_KUBERNETES_PVC_QUANTITY: {{ .Values.global.pvcClaim }}
  CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "true"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER: "{{ .Values.global.securityContext.runAsUser }}"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: "{{ .Values.global.securityContext.fsGroup }}"
  CHE_LOCAL_CONF_DIR: /etc/conf
  CHE_LOGS_DIR: /data/logs
  CHE_LOG_LEVEL: "INFO"
  CHE_MULTIUSER: {{ .Values.global.multiuser | quote }}
  CHE_OAUTH_GITHUB_CLIENTID: {{ .Values.global.gitHubClientID | quote}}
  CHE_OAUTH_GITHUB_CLIENTSECRET: {{ .Values.global.gitHubClientSecret | quote}}
  CHE_PREDEFINED_STACKS_RELOAD__ON__START: "false"
  JAVA_OPTS: "-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms20m "
  CHE_WORKSPACE_AUTO_START: "false"
{{- if .Values.global.tls.enabled }}
  CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"kubernetes.io/ingress.class": "nginx", "kubernetes.io/tls-acme": "true", "{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/rewrite-target": "/","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect": "true","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout": "3600","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout": "3600"}'
{{- else }}
  CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"kubernetes.io/ingress.class": "nginx", "{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/rewrite-target": "/","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect": "false","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout": "3600","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout": "3600"}'
{{- end }}
  CHE_INFRA_KUBERNETES_SERVER__STRATEGY: {{ .Values.global.serverStrategy }}
  CHE_LOGGER_CONFIG: {{ .Values.global.log.loggerConfig | quote}}
  CHE_LOGS_APPENDERS_IMPL: {{ .Values.global.log.appenderName }}
  CHE_WORKSPACE_HTTP__PROXY: {{ .Values.cheWorkspaceHttpProxy | quote}}
  CHE_WORKSPACE_HTTPS__PROXY: {{ .Values.cheWorkspaceHttpsProxy | quote}}
  CHE_WORKSPACE_NO__PROXY: {{ .Values.cheWorkspaceNoProxy | quote}}
  CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: '{{ .Values.global.workspaceIdleTimeout }}'
{{- if .Values.workspaceDefaultRamRequest }}
  CHE_WORKSPACE_DEFAULT_MEMORY_REQUEST_MB: {{ .Values.workspaceDefaultRamRequest }}
{{- end }}
{{- if .Values.workspaceDefaultRamLimit }}
  CHE_WORKSPACE_DEFAULT_MEMORY_LIMIT_MB: {{ .Values.workspaceDefaultRamLimit }}
{{- end }}
{{- if .Values.che.workspace.devfileRegistryUrl }}
  CHE_WORKSPACE_DEVFILE__REGISTRY__URL: {{ .Values.che.workspace.devfileRegistryUrl }}
{{- end }}
{{- if .Values.che.workspace.pluginRegistryUrl }}
  CHE_WORKSPACE_PLUGIN__REGISTRY__URL: {{ .Values.che.workspace.pluginRegistryUrl }}
{{- end }}
{{- if .Values.workspaceSidecarDefaultRamLimit }}
  CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB: {{ .Values.workspaceSidecarDefaultRamLimit }}
{{- end }}
{{- if .Values.global.cheWorkspaceClusterRole }}
  CHE_INFRA_KUBERNETES_CLUSTER__ROLE__NAME: {{ .Values.global.cheWorkspaceClusterRole }}
{{- end }}
  CHE_CORS_ENABLED: "true"
  CHE_CORS_ALLOW__CREDENTIALS: "false"
  CHE_CORS_ALLOWED__ORIGINS: "*"
  CHE_WSAGENT_CORS_ENABLED: "true"
  CHE_WSAGENT_CORS_ALLOW__CREDENTIALS: "true"
  CHE_WSAGENT_CORS_ALLOWED__ORIGINS: "NULL"
  CHE_TRACING_ENABLED: {{ .Values.global.tracingEnabled | quote }}
  JAEGER_ENDPOINT: "http://jaeger-collector:14268/api/traces"
  JAEGER_SERVICE_NAME: "che-server"
  JAEGER_SAMPLER_MANAGER_HOST_PORT: "jaeger:5778"
  JAEGER_SAMPLER_TYPE: "const"
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_REPORTER_MAX_QUEUE_SIZE: "10000"
  CHE_METRICS_ENABLED: {{ .Values.global.metricsEnabled | quote }}
