#
# Copyright (c) 2012-2017 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if .Values.registry }}
{{- if and .Values.registry.password .Values.registry.username }}
# When creating a pod based on an image that resides in a private Docker registry (a secure registry protected by basic authentication),
# one must specify an imagePullSecrets as part of the pod's spec.
# (see https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret)

# This resource creates a docker registry pull secret that's based on values provided in values.yaml (it relies on a template defined in _secretHelper.tpl). The secret must be deployed to
# the same namespace in which the pod will be created.
apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
