version: '2'
services:
  selenium_hub:
    image: selenium/hub:3.141.59-dubnium
    container_name: selenium_hub
    ports:
      - 4444:4444
    environment:
      - GRID_TIMEOUT=900
      - GRID_BROWSER_TIMEOUT=900
      - JAVA_OPTS=-Xms512m -Xmx1024m -Djava.security.egd=file:/dev/./urandom
      - GRID_CLEAN_UP_CYCLE=5000
    ulimits:
      nproc: 163840
      nofile:
        soft: 163840
        hard: 163840
    restart: always
    networks:
      - selenium_grid_internal

  chromenode:
    image: selenium/node-chrome${NODE_CHROME_DEBUG_SUFFIX}:3.141.59-dubnium
    depends_on:
      - selenium_hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
      - SCREEN_HEIGHT=1080
      - SCREEN_WIDTH=1920
      - SCREEN_DEPTH=24
    ports:
      - 5900
      - 5555
    networks:
      - selenium_grid_internal
    ulimits:
      nproc: 163840
      nofile:
        soft: 163840
        hard: 163840
    restart: always
    shm_size: 1g

networks:
    selenium_grid_internal:
