#
# Copyright (c) 2012-2017 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Namespace -}} -keycloak-role-binding
roleRef:
  kind: Role
  name: che-endpoints-monitor
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: che-keycloak
  namespace: {{ .Release.Namespace }}
