apiVersion: v1
kind: BuildConfig
metadata:
  name: postgres-for-che
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'postgres:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    images:
      - from:
          kind: ImageStreamTag
          name: 'che-init:latest'
        paths:
          - destinationDir: ./
            sourcePath: /etc/puppet/modules/postgres/templates/init-che-user.sh.erb
          - destinationDir: .s2i/bin/
            sourcePath: /files/s2i/postgres/assemble
          - destinationDir: .s2i/bin/
            sourcePath: /files/s2i/postgres/run
    type: Image
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'postgres-source:latest'
    type: Source
  triggers:
  - type: "ConfigChange"
  - type: "ImageChange" 
    imageChange: {}
  - type: "ImageChange" 
    imageChange:
      from:
        kind: "ImageStreamTag"
        name: "che-init:latest"
status:
