#
# Copyright (c) 2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

global:
  ingress:
    class: "nginx"

cheDevfileRegistry:
  image: quay.io/eclipse/che-devfile-registry:7.28.0
  imagePullPolicy: Always
  memoryLimit: 256Mi
  memoryRequests: 16Mi
