#
# Copyright (c) 2012-2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

---
kind: Template
apiVersion: v1
metadata:
  name: keycloak
  annotations:
    description: Che
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: keycloak
  spec:
    replicas: 1
    selector:
      app: keycloak
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: keycloak
      spec:
        containers:
        - env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: POSTGRES_PORT_5432_TCP_ADDR
            value: postgres
          - name: POSTGRES_PORT_5432_TCP_PORT
            value: "5432"
          - name: POSTGRES_DATABASE
            value: keycloak
          - name: POSTGRES_USER
            value: keycloak
          - name: POSTGRES_PASSWORD
            value: keycloak
          - name: KEYCLOAK_USER
            value: "${KEYCLOAK_USER}"
          - name: KEYCLOAK_PASSWORD
            value: "${KEYCLOAK_PASSWORD}"
          - name: PROTOCOL
            value: "${PROTOCOL}"
          - name: ROUTING_SUFFIX
            value: "${ROUTING_SUFFIX}"
          - name: CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD
            value: "${CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD}"
          - name: CHE_SELF__SIGNED__CERT
            valueFrom:
              secretKeyRef:
                key: ca.crt
                name: self-signed-certificate
                optional: true
          image: '${IMAGE_KEYCLOAK}:${KEYCLOAK_IMAGE_TAG}'
          command: ["/scripts/kc_realm_user.sh"]
          imagePullPolicy: "${KEYCLOAK_IMAGE_PULL_POLICY}"
          name: keycloak
          livenessProbe:
            failureThreshold: 11
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 30
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: auth/js/keycloak.js
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: 1536Mi
            requests:
              memory: 1024Mi
          volumeMounts:
          - mountPath: /opt/jboss/keycloak/standalone/data
            name: keycloak-data
          - mountPath: /opt/jboss/keycloak/standalone/log
            name: keycloak-log
        restartPolicy: Always
        volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
        - name: keycloak-log
          persistentVolumeClaim:
            claimName: keycloak-log
    test: false
- apiVersion: v1
  kind: Service
  metadata:
    name: keycloak
  spec:
    ports:
    - name: "5050"
      port: 5050
      targetPort: 8080
    selector:
      app: keycloak

- apiVersion: v1
  kind: Route
  metadata:
    name: keycloak
  spec:
    to:
      kind: Service
      name: keycloak
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: keycloak-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: keycloak-log
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

parameters:
- name: PROTOCOL
  displayName: htpps or http protocol
  description: Protocol to be used in Che communications
  value: http
- name: KEYCLOAK_USER
  displayName: Keycloak admin user
  description: Default Keycloak admin user
  value: "admin"
- name: KEYCLOAK_PASSWORD
  displayName: Keycloak admin password
  description: Default Keycloak admin password. Can be changed after login
  value: "admin"
- name: ROUTING_SUFFIX
  displayName: Routing suffix of your OpenShift cluster
  description: This is the suffix appended to routes in your OpenShift cluster <route>.<project>.<routing_suffix>
- name: KEYCLOAK_IMAGE_TAG
  displayName: Eclipse Che version
  description: Eclipse Che version which defaults to nightly
  value: 'nightly'
- name: IMAGE_KEYCLOAK
  displayName: Keycloak Image
  description: Keycloak Image. Defaults to docker.io/eclipse/che-keycloak
  value: 'eclipse/che-keycloak'
- name: CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD
  displayName: Require admin password update
  description: Ask for a password update after 1st login by admin user
  value: "true"
- name: KEYCLOAK_IMAGE_PULL_POLICY
  displayName: Keycloak image pull policy
  description: Always pull by default. Can be IfNotPresent
  value: 'Always'
labels:
  app: keycloak
  template: keycloak
