# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
kind: Template
apiVersion: v1
metadata:
  name: che
  annotations:
    description: Che
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: keycloak
    name: keycloak
  spec:
    replicas: 1
    selector:
      io.kompose.service: keycloak
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: keycloak
      spec:
        containers:
        - env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POSTGRES_PORT_5432_TCP_ADDR
            value: postgres
          - name: POSTGRES_PORT_5432_TCP_PORT
            value: "5432"
          - name: POSTGRES_DATABASE
            value: keycloak
          - name: POSTGRES_USER
            value: keycloak
          - name: POSTGRES_PASSWORD
            value: keycloak
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
          - name: PROTOCOL
            value: "${PROTOCOL}"
          - name: ROUTING_SUFFIX
            value: "${ROUTING_SUFFIX}"
          - name: CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD
            value: "${CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD}"
          image: '${IMAGE_KEYCLOAK}:${CHE_VERSION}'
          imagePullPolicy: Always
          name: keycloak
          livenessProbe:
            failureThreshold: 11
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 30
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: auth/js/keycloak.js
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: 1536Mi
            requests:
              memory: 1024Mi
          volumeMounts:
          - mountPath: /opt/jboss/keycloak/standalone/data
            name: keycloak-data
          - mountPath: /opt/jboss/keycloak/standalone/log
            name: keycloak-log
        restartPolicy: Always
        volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
        - name: keycloak-log
          persistentVolumeClaim:
            claimName: keycloak-log
    test: false
  status: {}

- apiVersion: v1
  kind: Service
  metadata:
    name: "keycloak"
  spec:
    ports:
    - name: "5050"
      port: 5050
      targetPort: 8080
    selector:
      io.kompose.service: keycloak
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Route
  metadata:
    name: "keycloak"
  spec:
    port:
      targetPort: '5050'
    to:
      kind: Service
      name: "keycloak"
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      io.kompose.service: keycloak-data
    name: keycloak-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status: {}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      io.kompose.service: keycloak-log
    name: keycloak-log
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status: {}

parameters:
- name: PROTOCOL
  displayName: htpps or http protocol
  description: Protocol to be used in Che communications
  value: http
- name: ROUTING_SUFFIX
  displayName: Routing suffix of your OpenShift cluster
  description: This is the suffix appended to routes in your OpenShift cluster <route>.<project>.<routing_suffix>
- name: CHE_VERSION
  displayName: Eclipse Che version
  description: Eclipse Che version which defaults to nightly
  value: nightly
- name: IMAGE_KEYCLOAK
  displayName: Keycloak Image
  description: Keycloak Image. Defaults to docker.io/eclipse/che-keycloak
  value: eivantsov/keycloak
