[[constraint]]
 name = "github.com/eclipse/che-go-jsonrpc"
 version = "=0.2.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "=3.1.0"

[[constraint]]
 name = "github.com/gorilla/websocket"
 revision = "361d4c0ffd78338ebe0a9e6320cdbe115d7dc026"

[[constraint]]
 name = "github.com/kr/pty"
 version = "=1.1.2"

[[constraint]]
 name = "github.com/julienschmidt/httprouter"
 revision = "4563b0ba73e4db6c6423b60a26f3cadd2e9a1ec9"


[prune]
  go-tests = true
  unused-packages = true
