#
# Copyright (c) 2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if not (and (eq .Values.global.serverStrategy "single-host") (eq .Values.global.singleHostExposure "gateway")) }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plugin-registry
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class | quote }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout: "3600"
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout: "3600"
{{- if .Values.global.tls.enabled }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
{{- if or (eq .Values.global.serverStrategy "default-host") (eq .Values.global.serverStrategy "single-host") }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/rewrite-target: "/$1"
{{- end }}
spec:
  rules:
{{- if eq .Values.global.serverStrategy "default-host" }}
  - http:
      paths:
      - path: /plugin-registry/(.*)
{{- else if eq .Values.global.serverStrategy "single-host" }}
  - host: {{ template "pluginRegistryHost" . }}
    http:
      paths:
      - path: /plugin-registry/(.*)
{{- else }}
  - host: {{ template "pluginRegistryHost" . }}
    http:
      paths:
      - path: /
{{- end }}
        backend:
          serviceName: plugin-registry
          servicePort: 8080
{{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - {{ template "pluginRegistryHost" . }}
    secretName: {{ .Values.global.tls.secretName }}
{{- end -}}

{{- end }}
