#
# Copyright (c) 2012-2017 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: "keycloak"
spec:
  ports:
  - name: "5050"
    port: 5050
    targetPort: 8080
  selector:
    io.kompose.service: keycloak
status:
  loadBalancer: {}
