#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# Eclipse Che workflow for checking repository list in CONTRIBUTING.md file
name: CI

# Trigger the workflow on push or pull request
on: 
  push:
    paths:
      - '.repositories.yaml'
  pull_request:
    paths:
      - '.repositories.yaml'
jobs:
  check-contributing-up-to-date:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout che-theia source code
    - name: check
      run: |
        ./.repositories-update-contributing.sh check
