#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Release changelog

on:
  push:
    tags:
    - '7.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'The version that is going to be released. Should be in format 7.y.z'
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Set up GH checkout and tokens
        run: |
          git config --global user.name "Mykhailo Kuznietsov"
          git config --global user.email "mkuznets@redhat.com"
          git config --global push.default matching
          export GITHUB_TOKEN=${{ secrets.CHE_BOT_GITHUB_TOKEN }}
          export CHE_BOT_GITHUB_TOKEN=${{ secrets.CHE_BOT_GITHUB_TOKEN }}
      -
        name: Prepare
        id: prepare
        run: |
          if [[ "${{ github.event.inputs.version }}" != "" ]]; then
            echo ::set-output name=release_version::${{ github.event.inputs.version }}
            release_version=${{ github.event.inputs.version }}
          elif [[ "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo ::set-output name=release_version::${GITHUB_REF#refs/tags/}
            release_version=${GITHUB_REF#refs/tags/}
          else
            echo "No version set, and no tag triggered this action, so nothing to do!"
            exit 1
          fi

          [[ $release_version =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]] && XX=${BASH_REMATCH[1]}; YY=${BASH_REMATCH[2]}; ZZ=${BASH_REMATCH[3]}
          # roll back from 7.28.2 -> 7.28.1; for 7.28.0 -> 7.27.2
          # TODO or do we want 7.28.0 -> 7.27.0 to roll up all issues since last .0 release?
          (( ZZ=ZZ-1 )); if [[ $ZZ -lt 0 ]]; then (( ZZ=ZZ+3 )); (( YY=YY-1 )); fi
          previous_version="${XX}.${YY}.${ZZ}"
          echo "For release_version = $release_version, got previous_version = $previous_version"
          echo ::set-output name=previous_version::${previous_version}
      - name: Create changelog
        id: generate-release-changelog
        # wrapper for https://github.com/github-changelog-generator/github-changelog-generator
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        env:
          GITHUB_TOKEN: ${{ secrets.CHE_BOT_GITHUB_TOKEN }}
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHE_BOT_GITHUB_TOKEN }}
        with:
          repo: eclipse/che 
          # output: CHANGELOG-next.md
          dateFormat: "%Y-%m-%d"
          stripHeaders: "true"
          stripGeneratorNotice: "true"
          maxIssues: 150
          verbose: true
          releaseBranch: master # TODO: change to main
          onlyLastTag: "false" # must set false, else dueTag=null and sinceTag=$(git describe --abbrev=0 --tags "$(git rev-list --tags --skip=1 --max-count=1)")
          dueTag: "${{ steps.prepare.outputs.release_version }}" # issues up to the current release tag
          sinceTag: "${{ steps.prepare.outputs.previous_version }}" # issues since the previous tag
          filterByMilestone: false # this requires that we get good at setting milestone when something is actually DONE rather than when we think it'll be done
          pullRequests: false # only include issues, not PRs, since PRs span multiple repos and are too noisy to include
          issuesWoLabels: false # no labels? no logged change
          issues: true # closed issues
          # issueLineLabels: "ALL" # doesn't work - /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/section.rb:52:in `get_string_for_issue': undefined method `line_labels_for' for #<GitHubChangelogGenerator::Section:0x00005608809a9988> (NoMethodError)
          compareLink: false
          unreleased: true # show unreleased, but closed items
          configureSections: '{
            "enh-epic-ux":{"prefix":"**Enhancements, Epics, and UX**","labels":["kind/enhancement,kind/epic,kind/ux"]}, 
            "sprint-current":{"prefix":"**Issues in Current Sprint:**","labels":["sprint/current"]}, 
            "new-noteworthy":{"prefix":"**New and Noteworthy Issues:**","labels":["new&noteworthy"]}}'
          excludeTags: 'sprint/next,roadmap/3-months,roadmap/6-months,roadmap/1-year,kind/planning,status/duplicate,status/in-progress,status/need-triage' # comma,delimited,list,of,tags
          # includeLabels: ''
          excludeLabels: "kind/release"
          bugsLabel: "**Bugs fixed**"
          bugLabels: "kind/bug"
          token: ${{ secrets.CHE_BOT_GITHUB_TOKEN }} 
      - name: Create GH Release
        id: create_release
        uses: ncipollo/release-action@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.CHE_BOT_GITHUB_TOKEN }} 
        with:
          allowUpdates: true
          body: ${{ steps.generate-release-changelog.outputs.changelog }}
          draft: false
          name: "Eclipse Che ${{ steps.prepare.outputs.release_version }}"
          omitBodyDuringUpdate: false
          omitNameDuringUpdate: false
          prerelease: false
          tag: "${{ steps.prepare.outputs.release_version }}"
          token: ${{ secrets.CHE_BOT_GITHUB_TOKEN }}
